// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Email.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class EmailProviderConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the EmailProviderConfiguration class.
        /// </summary>
        public EmailProviderConfiguration()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailProviderConfiguration class.
        /// </summary>
        public EmailProviderConfiguration(System.Guid? id = default(System.Guid?), string configurationName = default(string), System.Guid? subscriptionId = default(System.Guid?), bool? isApproved = default(bool?), System.DateTime? createdDateTime = default(System.DateTime?), ProviderConfigurationStatus providerConfigurationStatus = default(ProviderConfigurationStatus), IList<EmailTemplate> templates = default(IList<EmailTemplate>))
        {
            Id = id;
            ConfigurationName = configurationName;
            SubscriptionId = subscriptionId;
            IsApproved = isApproved;
            CreatedDateTime = createdDateTime;
            ProviderConfigurationStatus = providerConfigurationStatus;
            Templates = templates;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "configurationName")]
        public string ConfigurationName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public System.Guid? SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isApproved")]
        public bool? IsApproved { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDateTime")]
        public System.DateTime? CreatedDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "providerConfigurationStatus")]
        public ProviderConfigurationStatus ProviderConfigurationStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templates")]
        public IList<EmailTemplate> Templates { get; private set; }

    }
}
