// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Email.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class EmailDetailsResponse
    {
        /// <summary>
        /// Initializes a new instance of the EmailDetailsResponse class.
        /// </summary>
        public EmailDetailsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailDetailsResponse class.
        /// </summary>
        public EmailDetailsResponse(System.Guid? requestId = default(System.Guid?), System.Guid? subscriptionId = default(System.Guid?), System.Guid? providerConfigurationId = default(System.Guid?), System.Guid? templateId = default(System.Guid?), bool? isSentToProvider = default(bool?), System.DateTime? sentToProviderDateTime = default(System.DateTime?), string callbackUrl = default(string), IList<Attachment> attachments = default(IList<Attachment>))
        {
            RequestId = requestId;
            SubscriptionId = subscriptionId;
            ProviderConfigurationId = providerConfigurationId;
            TemplateId = templateId;
            IsSentToProvider = isSentToProvider;
            SentToProviderDateTime = sentToProviderDateTime;
            CallbackUrl = callbackUrl;
            Attachments = attachments;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestId")]
        public System.Guid? RequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public System.Guid? SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "providerConfigurationId")]
        public System.Guid? ProviderConfigurationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templateId")]
        public System.Guid? TemplateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isSentToProvider")]
        public bool? IsSentToProvider { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sentToProviderDateTime")]
        public System.DateTime? SentToProviderDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "callbackUrl")]
        public string CallbackUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attachments")]
        public IList<Attachment> Attachments { get; set; }

    }
}
