// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Email.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MSExchangeConfigurationUpdateRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MSExchangeConfigurationUpdateRequest class.
        /// </summary>
        public MSExchangeConfigurationUpdateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MSExchangeConfigurationUpdateRequest class.
        /// </summary>
        /// <param name="configurationName">A custom name that can be used to
        /// later understand the purpose of
        /// this provider configuration.</param>
        public MSExchangeConfigurationUpdateRequest(string configurationName = default(string))
        {
            ConfigurationName = configurationName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a custom name that can be used to later understand the
        /// purpose of
        /// this provider configuration.
        /// </summary>
        [JsonProperty(PropertyName = "configurationName")]
        public string ConfigurationName { get; set; }

    }
}
