// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Email.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MSExchangeConfigurationResponse
    {
        /// <summary>
        /// Initializes a new instance of the MSExchangeConfigurationResponse
        /// class.
        /// </summary>
        public MSExchangeConfigurationResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MSExchangeConfigurationResponse
        /// class.
        /// </summary>
        public MSExchangeConfigurationResponse(System.Guid? id = default(System.Guid?), string configurationName = default(string), string fromAddress = default(string), System.Guid? subscriptionId = default(System.Guid?), bool? isApproved = default(bool?), IList<EmailTemplate> templates = default(IList<EmailTemplate>))
        {
            Id = id;
            ConfigurationName = configurationName;
            FromAddress = fromAddress;
            SubscriptionId = subscriptionId;
            IsApproved = isApproved;
            Templates = templates;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "configurationName")]
        public string ConfigurationName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fromAddress")]
        public string FromAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public System.Guid? SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isApproved")]
        public bool? IsApproved { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templates")]
        public IList<EmailTemplate> Templates { get; set; }

    }
}
