// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Email.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProviderConfigurationStatus
    {
        /// <summary>
        /// Initializes a new instance of the ProviderConfigurationStatus
        /// class.
        /// </summary>
        public ProviderConfigurationStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProviderConfigurationStatus
        /// class.
        /// </summary>
        public ProviderConfigurationStatus(bool? isDeleted = default(bool?), string errorReason = default(string))
        {
            IsDeleted = isDeleted;
            ErrorReason = errorReason;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDeleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorReason")]
        public string ErrorReason { get; set; }

    }
}
