// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Email.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RecipientEmail
    {
        /// <summary>
        /// Initializes a new instance of the RecipientEmail class.
        /// </summary>
        public RecipientEmail()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RecipientEmail class.
        /// </summary>
        public RecipientEmail(IList<EmailAddress> to = default(IList<EmailAddress>), IList<EmailAddress> cc = default(IList<EmailAddress>), IList<EmailAddress> bcc = default(IList<EmailAddress>))
        {
            To = to;
            Cc = cc;
            Bcc = bcc;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public IList<EmailAddress> To { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cc")]
        public IList<EmailAddress> Cc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bcc")]
        public IList<EmailAddress> Bcc { get; set; }

    }
}
