// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Email.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Schedule
    {
        /// <summary>
        /// Initializes a new instance of the Schedule class.
        /// </summary>
        public Schedule()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Schedule class.
        /// </summary>
        public Schedule(ScheduleTime fromDateTime, ScheduleTime toDateTime)
        {
            FromDateTime = fromDateTime;
            ToDateTime = toDateTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fromDateTime")]
        public ScheduleTime FromDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "toDateTime")]
        public ScheduleTime ToDateTime { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (FromDateTime == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FromDateTime");
            }
            if (ToDateTime == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ToDateTime");
            }
            if (FromDateTime != null)
            {
                FromDateTime.Validate();
            }
            if (ToDateTime != null)
            {
                ToDateTime.Validate();
            }
        }
    }
}
