// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Email.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SendEmailResponse
    {
        /// <summary>
        /// Initializes a new instance of the SendEmailResponse class.
        /// </summary>
        public SendEmailResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SendEmailResponse class.
        /// </summary>
        /// <param name="emailRequestId">A unique identifier for the
        /// Email.</param>
        public SendEmailResponse(System.Guid emailRequestId)
        {
            EmailRequestId = emailRequestId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a unique identifier for the Email.
        /// </summary>
        [JsonProperty(PropertyName = "emailRequestId")]
        public System.Guid EmailRequestId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
