// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Logic.Email.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TemplateResponse
    {
        /// <summary>
        /// Initializes a new instance of the TemplateResponse class.
        /// </summary>
        public TemplateResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TemplateResponse class.
        /// </summary>
        public TemplateResponse(System.Guid? templateId = default(System.Guid?))
        {
            TemplateId = templateId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templateId")]
        public System.Guid? TemplateId { get; set; }

    }
}
